### ISSUE TITLE
MIDI-In: Cannot find Matriarch!

### ISSUE THREAD

**Issue by drbronner** [mreid/matriarch-editor#4] opened 2022-07-20 04:46 UTC
Hi there,

I’m using the Matriarch Global Settings Editor with Chrome on a mac m1. My Matriarch is connected via USB, and I’m able to send and receive MIDI to it in my DAW. I have allowed Chrome to use MIDI on the editor page. However, when I go to the editor, I get the following status:

> MIDI-Out: Moog Matriarch MIDI-In: Cannot find Matriarch!

and all the controls are greyed out. I’m not sure how to proceed from here. Do you have any suggestions?

Thanks!

**Comment by mreid** [comment] 2022-08-01 01:07
Hi Galen,

That's strange. The set up you've described seems identical to mine (M1 mac
and Chrome) which works fine.

The only thing you might want to check is whether the Matriarch has the
word "Matriarch" in its name in the "Audio & MIDI" setting panel. The
editor will only work if the Matriarch is named "Matriarch" according to
the operating system or whatever is controlling MIDI.

Hope that helps,

Mark

**Comment by denisngc0** [comment] 2022-11-04 16:41
Same problem here. But I can tell it started after I updated my MacOS version. MIDI works normally, just the page can't identify my Matriarch, whereas it's clearly working with my DAW, and visible on the MIDI Editor.

**Comment by zkleinfeld** [comment] 2022-11-11 18:35
Had same issue after updating to macOs 12.6.1. After a few days, Chrome updated and I was re-prompted to Allow Midi (despite the site already being allowed) and now it works again.

**Comment by mreid** [comment] 2022-11-13 07:44
This should be fixed now. 

For anyone who might be interested: as far as I can tell the issue was accidentally caused by me reconfiguring my web site to be hosted at GitHub. When I hosted my site here GitHub redirected mreid.github.io (which is where the Matriarch editor was hosted) to mark.reid.name (my domain). I did not realise this would affect how the JavaScript for the Matriarch editor was served. It seems like (perhaps due to https certificate changes) browsers stopped "trusting" the editor code that was being imported from a different place.

I've now made some updates that should fix that issue. If you refresh your browsers or go to https://mark.reid.name/matriarch-editor/ the editor should be working again.

Apologies for any inconvenience.

**Closed as completed by mreid** 2022-11-13 07:44 UTC
